---
apiVersion: v2
appVersion: 15 # https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
description: wg-easy
name: wg-easy
version: 2.0.2
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 2.6.0
