{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "template.fullname" . }}-pvc # Generate a unique name for the PVC
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
---
{{- if and .Values.mongodb.persistence.enabled (not .Values.mongodb.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "template.fullname" . }}-mongodb-pvc # Generate a unique name for the MongoDB PVC
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
{{- end }}